/*
 * This source file was generated by the Gradle 'init' task
 */
package student;

import java.io.IOException;
import calculator.CalculatorConsoleService;

public class App {

    public static void main(String[] args) throws IOException {
        new CalculatorConsoleService().run();
    }
}
