/*
 * This source file was generated by the Gradle 'init' task
 */
package student;

// import studentinfo.StudentInfoService;
import java.io.IOException;
import java.util.Scanner;

import calculator.Calculator;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import org.jline.utils.NonBlockingReader;

public class App {

    public static void main(String[] args) throws IOException {
        try (Scanner scanner = new Scanner(System.in)) {
            // This Student Package is for demonstration of OOP concepts in Java,
            // specifically encapsulation and abstraction.
            // System.out.print("Enter student ID: ");
            // int id = Integer.parseInt(scanner.nextLine().trim());
            // scanner.close();

            // StudentInfoService service = new StudentInfoService();
            // var result = service.getResultById(id);
            // if (result != null) {
            // System.out.println("Student Found Id: " + result.getId());
            // System.out.println("Student Found Name: " + result.getName());
            // System.out.println("Student Found Grade: " + result.getGrade());
            // System.out.println("Student Found Department: " + result.getDep());
            // }else{
            // System.out.println("No student found for ID=" + id);
            // }

            // This Calculator Package is for demonstration of OOP concepts in Java,
            // specifically encapsulation and abstraction.
            Calculator calculator = new Calculator();
            System.out.println("Enter first number: ");
            int a = Integer.parseInt(scanner.nextLine().trim());
            System.out.println("Enter second number: ");
            int b = Integer.parseInt(scanner.nextLine().trim());

            int choice;
            try {
                choice = selectOperationWithArrows();
            } catch (NoClassDefFoundError error) {
                choice = selectOperationWithNumberInput(scanner);
            }
            switch (choice) {
                case 1:
                    System.out.println("Result: " + calculator.add(a, b));
                    break;
                case 2:
                    System.out.println("Result: " + calculator.subtract(a, b));
                    break;
                case 3:
                    System.out.println("Result: " + calculator.multiply(a, b));
                    break;
                case 4:
                    System.out.println("Result: " + calculator.divide(a, b));
                    break;
                default:
                    System.out.println("Invalid choice");
            }
        }
    }

    private static int selectOperationWithArrows() throws IOException {
        String[] options = {"Add", "Subtract", "Multiply", "Divide"};
        int selected = 0;

        try (Terminal terminal = TerminalBuilder.builder().system(true).build()) {
            terminal.enterRawMode();
            NonBlockingReader reader = terminal.reader();

            while (true) {
                renderMenuSingleLine(terminal, options, selected);

                int ch = reader.read();
                if (ch == 27) {
                    int c2 = reader.read();
                    int c3 = reader.read();
                    if (c2 == 91 && c3 == 65) {
                        selected = (selected - 1 + options.length) % options.length;
                    }
                    if (c2 == 91 && c3 == 66) {
                        selected = (selected + 1) % options.length;
                    }
                } else if (ch == 10 || ch == 13) {
                    terminal.writer().println();
                    terminal.flush();
                    return selected + 1;
                }
            }
        }
    }

    private static void renderMenuSingleLine(Terminal terminal, String[] options, int selected) {
        StringBuilder line = new StringBuilder("\r\033[2KUse ↑/↓ and Enter: ");
        for (int i = 0; i < options.length; i++) {
            if (i == selected) {
                line.append("\u001B[7m>").append(options[i]).append("<\u001B[0m");
            } else {
                line.append(options[i]);
            }
            if (i < options.length - 1) {
                line.append(" | ");
            }
        }
        terminal.writer().print(line);
        terminal.flush();
    }

    private static int selectOperationWithNumberInput(Scanner scanner) {
        while (true) {
            System.out.println("Choose operation: 1) Add 2) Subtract 3) Multiply 4) Divide");
            String input = scanner.nextLine().trim();
            try {
                int choice = Integer.parseInt(input);
                if (choice >= 1 && choice <= 4) {
                    return choice;
                }
            } catch (NumberFormatException ignored) {
            }
            System.out.println("Invalid choice. Enter 1, 2, 3, or 4.");
        }
    }
}
